--MOVIES - 1:
--SELECT title, year, LENGTH
--FROM MOVIE
--WHERE YEAR < 2000 AND LENGTH > 120 OR LENGTH IS NULL

--MOVIES - 2:
--SELECT NAME, GENDER
--FROM MOVIESTAR
--WHERE YEAR(BIRTHDATE) > 1948 AND NAME LIKE 'J%' ORDER BY NAME DESC

--MOVIES - 3:
--SELECT STUDIONAME, COUNT(DISTINCT STARNAME) AS num_actors
--FROM MOVIE JOIN STARSIN ON MOVIETITLE = TITLE GROUP BY STUDIONAME HAVING COUNT(STARNAME) > 0

--MOVIES - 4:
--SELECT STARNAME, COUNT(MOVIETITLE)
--FROM STARSIN GROUP BY STARNAME

--MOVIES - 5:
--SELECT t2.STUDIONAME, t1.TITLE, t2.year
--FROM (SELECT STUDIONAME, MAX(YEAR) AS year FROM MOVIE GROUP BY STUDIONAME) t2 INNER JOIN MOVIE AS t1 ON t1.STUDIONAME = t2.STUDIONAME AND t1.YEAR = t2.year

--MOVIES - 6:
--SELECT TOP 1 NAME
--FROM MOVIESTAR
--WHERE GENDER = 'M' ORDER BY BIRTHDATE DESC

--MOVIES - 7: 
--SELECT t3.STUDIONAME, t3.STARNAME, t3.num_movies 
--FROM (SELECT STUDIONAME, STARNAME, COUNT(TITLE) AS num_movies FROM MOVIE RIGHT JOIN STARSIN ON MOVIETITLE = TITLE GROUP BY STUDIONAME, STARNAME) t3 INNER JOIN (SELECT STUDIONAME, MAX(num_movies) AS num_movies FROM (SELECT STUDIONAME, STARNAME, COUNT(TITLE) AS num_movies FROM MOVIE RIGHT JOIN STARSIN ON MOVIETITLE = TITLE GROUP BY STUDIONAME, STARNAME) t1 GROUP BY STUDIONAME) t2 ON t2.STUDIONAME = t3.STUDIONAME AND t2.num_movies = t3.num_movies

--MOVIES - 8:
--SELECT t1.TITLE, MOVIE.YEAR, count AS num_actors 
--FROM (SELECT TITLE, COUNT(STARNAME) AS count FROM MOVIE INNER JOIN STARSIN ON MOVIETITLE = TITLE GROUP BY TITLE HAVING COUNT(STARNAME) > 2) t1 INNER JOIN MOVIE ON t1.TITLE = MOVIE.TITLE