--MOVIES - 1:
--SELECT Address
--FROM STUDIO
--WHERE name='Disney'

--MOVIES - 2:
--SELECT BIRTHDATE
--FROM MOVIESTAR
--WHERE name LIKE 'Jack Nicholson'

--MOVIES - 3:
--SELECT starname
--FROM STARSIN
--WHERE MOVIEYEAR = 1980 or MOVIETITLE like 'Knight'

--MOVIES - 4:
--SELECT name
--FROM MOVIEEXEC
--WHERE NETWORTH > 10000000

--MOVIES - 5:
--SELECT name
--FROM MOVIESTAR
--WHERE GENDER LIKE 'm' OR ADDRESS LIKE 'Prefect Rd.'
