--MOVIES - 1:
--SELECT title, MOVIEEXEC.NAME 
--FROM MOVIE INNER JOIN MOVIEEXEC ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT# 
--WHERE PRODUCERC# = (SELECT PRODUCERC# FROM MOVIE WHERE TITLE = 'Star Wars')

--MOVIES - 2:
--SELECT DISTINCT MOVIEEXEC.NAME
--FROM STARSIN INNER JOIN MOVIE ON MOVIETITLE = TITLE INNER JOIN MOVIEEXEC ON CERT# = PRODUCERC#
--WHERE STARNAME = 'Harrison Ford'

--MOVIES - 3:
--SELECT DISTINCT STUDIONAME, STARNAME
--FROM MOVIE INNER JOIN STARSIN ON TITLE = MOVIETITLE ORDER BY STUDIONAME

--MOVIES - 4:
--SELECT STARNAME, NETWORTH, TITLE
--FROM STARSIN INNER JOIN MOVIE ON MOVIETITLE = TITLE INNER JOIN MOVIEEXEC ON CERT# = PRODUCERC#
--WHERE NETWORTH >= ALL(SELECT NETWORTH FROM MOVIEEXEC)

--MOVIES - 5:
--SELECT NAME, MOVIETITLE
--FROM MOVIESTAR LEFT JOIN STARSIN ON NAME = STARNAME
--WHERE MOVIETITLE IS NULL

