--MOVIES - 1:
--SELECT NAME 
--FROM MOVIESTAR 
--WHERE GENDER = 'F' AND NAME IN (SELECT NAME FROM MOVIEEXEC WHERE NETWORTH > 10000000)

--MOVIES - 2:
--SELECT NAME 
--FROM MOVIESTAR 
--WHERE NAME NOT IN (SELECT NAME FROM MOVIEEXEC)

--MOVIES - 3:
--SELECT TITLE 
--FROM MOVIE 
--WHERE LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE = 'Star Wars')

--MOVIES - 4:
--SELECT MOVIE.TITLE, ex.NAME 
--FROM MOVIE, (SELECT CERT#, NAME FROM MOVIEEXEC WHERE NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME = 'Merv Griffin')) ex 
--WHERE PRODUCERC# = CERT#