--SHIPS - 1:
--SELECT NAME 
--FROM SHIPS 
--WHERE CLASS IN (SELECT CLASS FROM CLASSES WHERE DISPLACEMENT > 50000);

--SHIPS - 2:
--SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS 
--FROM SHIPS INNER JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS 
--WHERE SHIPS.NAME IN (SELECT SHIP AS NAME FROM OUTCOMES WHERE BATTLE = 'Guadalcanal');

--SHIPS - 3:
--SELECT COUNTRY 
--FROM CLASSES 
--WHERE TYPE = 'bb' AND COUNTRY IN (SELECT COUNTRY FROM CLASSES WHERE TYPE = 'bc');

--SHIPS - 4:
--SELECT out1.SHIP 
--FROM OUTCOMES AS out1, OUTCOMES AS out2, BATTLES AS bat1, BATTLES AS bat2 
--WHERE out1.SHIP = out2.SHIP AND out1.RESULT='damaged' AND bat1.NAME = out1.BATTLE AND bat2.NAME = out2.BATTLE AND bat1.DATE < bat2.DATE