--SHIPS - 1:
--SELECT *
--FROM CLASSES INNER JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS

--SHIPS - 2:
--SELECT *
--FROM CLASSES LEFT JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS

--SHIPS - 3:
--SELECT CLASSES.COUNTRY, SHIPS.NAME 
--FROM SHIPS LEFT JOIN OUTCOMES ON OUTCOMES.SHIP = SHIPS.NAME INNER JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
--WHERE OUTCOMES.SHIP IS NULL

--SHIPS - 4:
--SELECT SHIPS.NAME AS 'Ship Name'
--FROM CLASSES INNER JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
--WHERE LAUNCHED = 1916 AND NUMGUNS >= 7

--SHIPS - 5:
--SELECT SHIP, BATTLE, DATE
--FROM OUTCOMES INNER JOIN BATTLES ON BATTLES.NAME = OUTCOMES.BATTLE
--WHERE RESULT = 'sunk'

--SHIPS - 6:
--SELECT NAME, DISPLACEMENT, LAUNCHED
--FROM CLASSES INNER JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS
--WHERE SHIPS.NAME = SHIPS.CLASS

--SHIPS - 7:
--SELECT *
--FROM CLASSES LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
--WHERE SHIPS.NAME IS NULL

--SHIPS - 8:
--SELECT SHIPS.NAME, DISPLACEMENT, NUMGUNS, RESULT
--FROM CLASSES INNER JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS INNER JOIN OUTCOMES ON OUTCOMES.SHIP = SHIPS.NAME
--WHERE OUTCOMES.BATTLE = 'North Atlantic'