--SHIPS - 1:
--SELECT CLASS, COUNTRY
--FROM CLASSES 
--WHERE NUMGUNS < 10

--SHIPS - 2:
--SELECT name as 'shipName'
--FROM SHIPS
--WHERE LAUNCHED < 1918

--SHIPS - 3:
--SELECT SHIP, BATTLE
--FROM OUTCOMES
--WHERE RESULT like 'sunk'

--SHIPS - 4:
--SELECT NAME
--FROM SHIPS
--WHERE NAME LIKE CLASS

--SHIPS - 5:
--SELECT NAME
--FROM SHIPS
--WHERE NAME LIKE 'R%'

--SHIPS - 6:
--SELECT NAME
--FROM SHIPS
--WHERE NAME LIKE '% %'