--SHIPS - 1:
--SELECT COUNT(DISTINCT CLASS) AS NO_classes 
--FROM CLASSES 
--WHERE TYPE = 'bb'

--SHIPS - 2:
--SELECT CLASS, AVG(NUMGUNS) AS AvgGuns
--FROM CLASSES
--WHERE TYPE = 'bb' GROUP BY CLASS

--SHIPS - 3:
--SELECT AVG(NUMGUNS) AS AvgGuns
--FROM CLASSES
--WHERE TYPE = 'bb'

--SHIPS - 4:
--SELECT CLASS, MIN(LAUNCHED) AS FirstYear, MAX(LAUNCHED) AS LastYear
--FROM SHIPS GROUP BY CLASS

--SHIPS - 5:
--SELECT class, COUNT(RESULT) AS NO_sunk
--FROM OUTCOMES JOIN SHIPS ON SHIPS.NAME = OUTCOMES.SHIP
--WHERE RESULT = 'sunk' GROUP BY CLASS

--SHIPS - 6:
--SELECT class, COUNT(RESULT) AS NO_sunk
--FROM OUTCOMES JOIN SHIPS ON SHIPS.NAME = OUTCOMES.SHIP
--WHERE RESULT = 'sunk' AND CLASS IN (SELECT CLASSES.CLASS FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS GROUP BY CLASSES.CLASS HAVING COUNT(CLASSES.CLASS) >= 2) GROUP BY CLASS

--SHIPS - 7:
--SELECT country, CAST(AVG(BORE) AS decimal(10,2)) AS AVGBore
--FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS GROUP BY COUNTRY
